@startuml

entity item {
    id
    --
    name
    descript
    width
    length
    height
    weight
    price
    links : charvar[]
    pictures : int[]
    categories : int[]
}
entity product {
    id
    --
    name
    descript
    price
    links : charvar[]
    delivery_types : int[]
    pictures : int[]
    categories : int[]
}
entity product_line {
    id
    --
    item_id
    product_id
    quantity
}
entity documentation_product {
    id
    --
    name
    descript
    data
    product_id
}
entity documentation_item {
    id
    --
    name
    descript
    data
    item_id
}
entity customer {
    id
    --
    name
    email
    password
    address_id
}
entity employee {
    id
    --
    name
    email
    password
    address_id
    role
}
entity orders {
    id
    --
    time_transaction
    time_delivery
    time_completion
    delivery_type_id
    customer_id
    employee_id
    price
}
entity order_line {
    id
    --
    order_id
    item_id
    quantity
}
entity delivery_type {
    id
    --
    name
    price
}
entity category {
    id
    --
    name
    common_denominators
}
entity address {
    id
    --
    street
    number
    floor
    zip_code
}
entity zip_code {
    code
    --
    city_name
}
entity picture {
    id
    --
    data : bytea
    link : varchar
}
entity product_spec_line {
    id
    --
    product_id
    spec_name : varchar
    spec_details : varchar
}

product_line "0..*" }o-- "1" item
product_line "0..*" }o-- "1" product

product " " --{ "0..*" category
product " " --{ "0..*" picture
product " " --{ "0..*" delivery_type

item " " --{ "0..*" category
item " " --{ "0..*" picture

product "1" ||--{ "0..*" product_spec_line

order_line "0..*" }o-- "1" orders
order_line "0..*" }o-- "1" item

documentation_product "1..*" }--|| "1" product
item "1" ||--|{ "1..*" documentation_item

orders "0..*" }|--|| "1" customer
orders "0..*" }|--|| "1" employee
orders "0..*" }--|| "1" delivery_type

customer " " --|| "1" address
employee " " --|| "1" address

address " " --|| "1" zip_code

@enduml