@startuml
@startuml

metaclass materiale <<lager>> {
  mål
  pris
  beskrivelse
  kategori
}

metaclass produkt {
  materialer
  beskrivelse
  mål / antal mm.
  pris
  status
  levering
  dokumentation f.eks. vejl.
  kategori
  yderligere specifikationer...
}

metaclass kunde {
  kontaktinfo
  korrespondence
  historik f.eks. bestillinger
}

metaclass ansat {
  kontaktinfo
  korrespondence
  rolle
}

metaclass bestilling {
  kunde
  ansat
  produkt
  dato/tid
}

metaclass kategori {
  fællesnævnere
}

metaclass lager {
    adresse
    materialer
    ansat
}

materiale "1..*" -- "0.." produkt
materiale "0..*" -- "0..*" lager

kunde "0.." -- "0..*" produkt

ansat "0..1" -- "0..*" kunde
ansat "0..1" -- "0..*" lager

kategori "1..*" -- "0..*" produkt

bestilling "0..*" -- "0..1" kunde
bestilling "0..*" -- "0..1" ansat
bestilling "0..*" -- "0..*" produkt

@enduml

@enduml